SELECT
 L_ORDERKEY AS ORDERID
,L_PARTKEY AS PARTID
,L_SUPPKEY AS SUPPLIERID
,L_LINENUMBER AS LINEID
,L_QUANTITY AS QUANTITY
,L_EXTENDEDPRICE AS EXTENDEDPRICE
,L_TAX AS TAX
,L_RETURNFLAG AS RETURNFLAG
,L_LINESTATUS AS LINESTATUS
,L_SHIPDATE AS SHIPDATE
,L_COMMITDATE AS COMMITDATE
,L_RECEIPTDATE AS RECEIPTDATE
,L_SHIPMODE AS SHIPMODE
,L_COMMENT AS "COMMENT"
FROM {{source ('landing','LINEITEM_SRC') }}

